name: workflow3.yml
on: push

jobs:
  check-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make lint

  build-c:
    needs: check-c
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: run make
        run: make build

  check-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: python script/mysystem/mysystem.py

  build-python:
    needs: check-python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - run: pip install ifaddr psutil pylint
      - run: pylint --disable=missing-docstring script/mysystem/mysystem.py

