name: workflow3.yml
on: push

jobs:
  build:
    name: Make
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: run make
        run: make build
