name: workflow2.yml
on: workflow_dispatch

jobs:
  build:
    name: Containers
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22
    steps:
      - name: information sur le stockage
        run: lsblk
      - name: information sur le noyau utilisé
        run: uname -a
